"""initial migration

Revision ID: ccab45594a99
Revises:
Create Date: 2022-05-23 18:56:10.542695

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ccab45594a99"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'collaborator', type_='foreignkey')
    # op.create_foreign_key(None, 'collaborator', 'board', ['board_id'], ['id'], ondelete='CASCADE')
    op.add_column("theme", sa.Column("description", sa.Text(), nullable=True))
    op.drop_column("theme", "info")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("theme", sa.Column("info", sa.TEXT(), nullable=True))
    op.drop_column("theme", "description")
    # op.drop_constraint(None, 'collaborator', type_='foreignkey')
    # op.create_foreign_key(None, 'collaborator', 'user', ['board_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
